Repository meilisearch/meilisearch-php, pull requests merged in 2020-09, with the labels that each got.

#80 MeiliSearch Bump to v0.14.0
  README.md
Labels: MeiliSearch bump

#81 Remove locked in dependency with guzzle 6 to allow any psr18 compatible http client
  README.md
  composer.json
  src/Http/Client.php
Labels: breaking-change

#85 Update version (v0.14.0) in MeiliSearch.php for the next release
  src/MeiliSearch.php
Labels: skip-changelog

#87 Update docs for HTTP Client compatibilities
  .code-samples.meilisearch.yaml
  README.md
Labels: skip-changelog

#90 Update version to create an alpha release
  src/MeiliSearch.php
Labels: skip-changelog

#93 Update version (v0.14.1) for the next release
  src/MeiliSearch.php
Labels: skip-changelog

#94 Docs guzzle7
  .code-samples.meilisearch.yaml
  README.md
  composer.json
  tests/Endpoints/ClientTest.php
Labels: skip-changelog

#96 Test compatible clients in CI
  .github/workflows/tests.yml
Labels: skip-changelog

#99 Update version (v0.14.2) for the next release
  src/MeiliSearch.php
Labels: skip-changelog

#100 Remove the ability to replace Response and Request Factories
  README.md
  src/Client.php
  src/Http/Client.php
Labels: breaking-change

#103 Remove Examples section
  README.md
Labels: skip-changelog

#102 Update docs for the HTTP client customization
  README.md
Labels: skip-changelog
