Repository meilisearch/meilisearch-php, pull requests merged in 2020-10, with the labels that each got.

#104 Update delete index to always return an array
  src/Delegates/HandlesIndex.php
  src/Endpoints/Indexes.php
Labels: Hacktoberfest, breaking-change

#106 Add dumps methods
  .code-samples.meilisearch.yaml
  src/Client.php
  src/Endpoints/Delegates/HandlesDumps.php
  src/Endpoints/Dumps.php
  tests/Endpoints/DumpTest.php
Labels: Hacktoberfest

#108 Update version for the next release (v0.15.0)
  src/MeiliSearch.php
Labels: skip-changelog

#109 Add Bors
  .github/workflows/tests.yml
  CONTRIBUTING.md
  bors.toml
Labels: skip-changelog

#110 Update README.md
  README.md
Labels: skip-changelog
