Repository meilisearch/meilisearch-php, pull requests merged in 2022-10, with the labels that each got.

#386 This will fix docs in batches sending same chunk
  src/Endpoints/Delegates/HandlesDocuments.php
Labels: bug

#389 Make possible for static analysis tools to detect return type of `Indexes::search`
  src/Endpoints/Indexes.php
  tests/Endpoints/SearchTest.php
Labels: enhancement

#392 Enforce strong type property - related with #385
  src/Client.php
Labels: enhancement

#391 Replace MEILISEARCH_HOST by MEILISEARCH_URL
  docker-compose.yml
  phpunit.xml.dist
  tests/TestCase.php
Labels: enhancement, skip-changelog

#393 Add PHP hosted documentation
  .github/workflows/docs.yml
Labels: enhancement

#394 Remove test path from phpDocumentor run
  .github/workflows/docs.yml
Labels: enhancement

#399 Implement methods for CSV and Ndjson batch adds
  src/Contracts/Http.php
  src/Endpoints/Delegates/HandlesDocuments.php
  src/Http/Client.php
  tests/Endpoints/DocumentsTest.php
Labels: enhancement
