Repository meilisearch/meilisearch-php, pull requests merged in 2023-03, with the labels that each got.

#472 Tests: switch expected and actual values for assertions
  tests/Contracts/CancelTasksQueryTest.php
  tests/Contracts/DeleteTasksQueryTest.php
  tests/Contracts/DocumentsQueryTest.php
  tests/Contracts/IndexesQueryTest.php
  tests/Contracts/KeysQueryTest.php
  tests/Contracts/TasksQueryTest.php
  tests/Endpoints/TasksTest.php
Labels: enhancement, skip-changelog

#480 Add CSV delimiter to csv document handler methods
  src/Endpoints/Delegates/HandlesDocuments.php
  tests/Endpoints/DocumentsTest.php
  tests/datasets/songs-custom-separator.csv
Labels: enhancement

#481 Add `multiSearch`
  composer.json
  src/Client.php
  src/Contracts/SearchQuery.php
  src/Endpoints/Delegates/HandlesMultiSearch.php
  tests/Contracts/CancelTasksQueryTest.php
  tests/Contracts/DeleteTasksQueryTest.php
  tests/Contracts/DocumentsQueryTest.php
  tests/Contracts/IndexesQueryTest.php
  tests/Contracts/KeysQueryTest.php
  tests/Contracts/TasksQueryTest.php
  tests/Endpoints/MultiSearchTest.php
  tests/Endpoints/TasksTest.php
Labels: enhancement

#488 Use wildcards in tests
  tests/Endpoints/TenantTokenTest.php
Labels: skip-changelog
