Repository meilisearch/meilisearch-php, pull requests merged in 2023-10, with the labels that each got.

#585 Fix passing empty masterkey
  src/Http/Client.php
  tests/Http/ClientTest.php
Labels: bug

#589 Add CI to update library version
  .github/workflows/update-version.yml
  CONTRIBUTING.md
Labels: maintenance

#591 Fix automation to update version
  .github/workflows/update-version.yml
Labels: skip-changelog
