Repository meilisearch/meilisearch-php, pull requests merged in 2023-09, with the labels that each got.

#571 [v1.4] Add word dictionary settings
  src/Endpoints/Delegates/HandlesSettings.php
  tests/Endpoints/IndexTest.php
  tests/Settings/WordDictionaryTest.php
Labels: enhancement

#572 [v1.4] Add separator tokens and non-separator tokens setting
  src/Endpoints/Delegates/HandlesSettings.php
  tests/Settings/NonSeparatorTokensTest.php
  tests/Settings/SeparatorTokensTest.php
Labels: enhancement

#579 Add code samples for v1.4.0
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#580 Remove useless code samples (not used by the docs anymore)
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#581 Fix failing documentation deployement
  .github/workflows/docs.yml
Labels: skip-changelog

#574 Changes related to the next Meilisearch release (v1.4.0)
  .code-samples.meilisearch.yaml
  src/Endpoints/Delegates/HandlesSettings.php
  tests/Endpoints/IndexTest.php
  tests/Settings/NonSeparatorTokensTest.php
  tests/Settings/SeparatorTokensTest.php
  tests/Settings/WordDictionaryTest.php
Labels: enhancement, Meilisearch bump
