Repository meilisearch/meilisearch-php, pull requests merged in 2024-09, with the labels that each got.

#674 Fix CS
  .php-cs-fixer.dist.php
Labels: maintenance

#673 Fix similar docs code sample
  .code-samples.meilisearch.yaml
Labels: documentation

#680 Fix code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog
