Repository meilisearch/meilisearch-php, pull requests merged in 2024-10, with the labels that each got.

#687 Ai powered api changes
  .code-samples.meilisearch.yaml
  src/Contracts/SimilarDocumentsQuery.php
  tests/Contracts/SimilarDocumentsQueryTest.php
  tests/Endpoints/SearchTest.php
  tests/Endpoints/SimilarDocumentsTest.php
  tests/Settings/EmbeddersTest.php
Labels: enhancement, breaking-change

#688 Multi search facet distribution
  src/Contracts/MultiSearchFederation.php
  tests/Contracts/MultiSearchFederationTest.php
  tests/Endpoints/MultiSearchTest.php
Labels: enhancement

#691 fix: pull the latest in the CI instead of forcing the v1.11
  .github/workflows/tests.yml
  docker-compose.yml
Labels: bug, CI
