Repository meilisearch/meilisearch-php, pull requests merged in 2024-12, with the labels that each got.

#696 Update CI to run with PHP 8.4
  .github/workflows/meilisearch-beta-tests.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  bors.toml
Labels: maintenance

#701 Make `hitsCount` always the number of `hits` (and not `totalHits` value)
  src/Search/SearchResult.php
Labels: bug

#709 Add batch progress
  tests/Endpoints/BatchesTest.php
Labels: enhancement

#711 Add 1.12 code samples
  .code-samples.meilisearch.yaml
Labels: maintenance

#710 Fix flaky tasks reverse test
  tests/Endpoints/TasksTest.php
Labels: maintenance
