Repository meilisearch/meilisearch-php, pull requests merged in 2025-05, with the labels that each got.

#754 Improve distinct attribute search tests
  tests/Endpoints/SearchTest.php
Labels: maintenance

#755 Do not modify http client state
  src/Contracts/Http.php
  src/Http/Client.php
Labels: enhancement

#756 Add more phpstan extensions
  .editorconfig
  composer.json
  phpstan.dist.neon
  phpstan.neon.dist
Labels: enhancement, maintenance
